apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  template:
    metadata:
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - image: docker.io/chanwit/worker:v1
          name: worker
      restartPolicy: Always
