---
apiVersion: v1
kind: Namespace
metadata:
  name: dockercoins
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dockercoins-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests
  prune: true
  wait: true
  targetNamespace: dockercoins
  sourceRef:
    kind: GitRepository
    name: flux-system
