apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  template:
    metadata:
      labels:
        io.kompose.service: webui
    spec:
      containers:
        - image: docker.io/chanwit/webui:v1
          name: webui
          ports:
            - containerPort: 8080
      restartPolicy: Always
